### PR TITLE
Add chlorophyll dataset to production

### PR DESCRIPTION
**Pull request by JessyBarrette**
# Final Submission
This is the final approval of the Chlorophyll Sample Datasets. You can revise the resulting aspect here:
## Provisional
This is related to issue #47 
- [x] Provisional ERDDAP Dataset: https://goose.hakai.org/erddap/tabledap/HakaiChlorophyllSampleProvisional.html
- [x] [CIOOS Metadata Form](https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/7U7b8oPpeTN6gjvXlUCTGJr5pga2/-McQFPAf457LB4-SWmyL)
## Research 
This is related to issue #32 
- [x] Research Dataset: https://goose.hakai.org/erddap/tabledap/HakaiChlorophyllSampleResearch.html
- [x] [CIOOS Metadata Form](https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/7U7b8oPpeTN6gjvXlUCTGJr5pga2/-MadZvZJ4ZeikpCgRcV8) 
 
related to #58

### CODE REVIEW

**Comment by jdelbel** [comment]
I'd like there to be another step for pushing the data to the research ready dataset - currently I think it is set to any AV flag being pushed, is this correct? Under the "Quality_level" tab there is a "Publication" option. Could this be used to decide whether the data are pushed to research?

**Comment by JessyBarrette** [comment]
yes for sure! Those are the levels available. Though I'm not sure if Principal Investigator has the same purpose. Your call
```
	'Raw',
	'Technician',
	'Technicianm',
	'Technicianr',
	'Technicianmr',
	'Principal Investigator',
	'Interum',
	'Publication',
	'Error'
```

**Comment by jdelbel** [comment]
Yeah they seem somewhat interchangeable. I think I will start using PC for when I have reviewed the data (as I hope to get Bryn doing QC when she returns) and then Publication for the research dataset.

Other than that, I want to look over the dataset again, but I think we can push.

**Comment by JessyBarrette** [comment]
ok as of now no data is at the Publication quality level

**Comment by JessyBarrette** [comment]
@jdelbel sorry I just realized that those datasets never made online yet. 

The Research one is still down since there's no data available as research ready yet. 

One thing missing from the metadata forms is your ORCID id. Do you have one already, I try to look for it but did see anything? If you don't please create one here: https://orcid.org/

This is often required now from different publication too. It will be good and help you being appropriately cited and know where you are.

**Comment by JessyBarrette** [comment]
I merge this regardless since the rest is related to the metadata form and can be updated anytime

**Pull request merged**
