### PR TITLE
add hakai erddap ctd tables to erddap schema

### PR DESCRIPTION
**Pull request by JessyBarrette**
I am getting ready to redirect the Hakai ERDDAP CTD datasets towards the Hakai database from the temporary files hosted on the server.

To proceed I need to get generate a view/table version of the hakai ctd. `ctd.ctd_file_cast_data`  and `ctd. ctd_post_qc_data` tables to retrieve exclusively the Hakai Institute CTD data.

Before merging here's two steps needed to discuss or apply:
- [x] ~View~ or Table? @fostermh any suggestion regarding that?
- [ ] The `ctd.ctd_post_qc_dat` from https://github.com/HakaiInstitute/hakai-database/pull/350#event-7350914599 needs to be made available on hakai db. Is there anything holding this @sorochak @fostermh

### CODE REVIEW

**Comment by JessyBarrette** [comment]
This is related to https://github.com/HakaiInstitute/hakai-ctd-processing-manual/issues/1

**Comment by n-a-t-e** [comment]
CTD data from our DB that is going to erddap should be either in files or tables, not views. Performance is way better with tables and there has been no issue with how that has been done up to now

**Comment by JessyBarrette** [comment]
@n-a-t-e  table sounds great to me!

**Comment by JessyBarrette** [comment]
I will manually generate those present table on hakai db and the present PR will joined to the associated datasets.xml later

**Pull request closed without merging**
