### PR TITLE
Add Hakai Mooring Water Properties Time series to production erddap

### PR DESCRIPTION
**Pull request by JessyBarrette**
This is the finalized submission of the Hakai Mooring Water Properties Timeseries Dataset related to #14

This datasets as of now is as of now only the Rivers Inlet Mooring CTD+DO data. Data was processed to remove data recorded prior and after deployment. Bad values were flagged manually which are likely related to sediments stuck within the conductivity cell. 

For review please review the following
ERDDAP Dataset: https://goose.hakai.org/erddap/tabledap/HakaiMooredTimeSeriesResearch.html
CKAN Record: https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/tV5qE0aUgaOjSVmgPgiZ6MyHuSy1/-MkEosZGlTnDy2oMp9nX

# Resulting Data
## Salinity
image
https://goose.hakai.org/erddap/tabledap/HakaiMooredTimeSeriesResearch.graph?time%2CPSALST01%2Cdepth&time%3E=2020-02-01T00%3A00%3A00Z&time%3C=2020-09-05T00%3A00%3A00Z&.draw=markers&.marker=3%7C5&.color=0x000000&.colorBar=%7C%7C%7C%7C%7C&.bgColor=0xffccccff

## Temperature
image
https://goose.hakai.org/erddap/tabledap/HakaiMooredTimeSeriesResearch.graph?time%2CTEMPS901%2Cdepth&time%3E=2020-02-01T00%3A00%3A00Z&time%3C=2020-09-05T00%3A00%3A00Z&.draw=markers&.marker=3%7C5&.color=0x000000&.colorBar=%7C%7C%7C%7C%7C&.bgColor=0xffccccff
## Dissolved Oxygen
image
https://goose.hakai.org/erddap/tabledap/HakaiMooredTimeSeriesResearch.graph?time%2CDOXYZZ01%2CPRESPR01&time%3E=2020-02-01T00%3A00%3A00Z&time%3C=2020-09-05T00%3A00%3A00Z&.draw=markers&.marker=3%7C5&.color=0x000000&.colorBar=%7C%7C%7C%7C%7C&.bgColor=0xffcc

# Data comparison versus CTD Profiles completed at DFO2
### 94dBar
MooringDFO3_CompareWithCTD_94dBar_20200212to20200828

### 247dBar
MooringDFO3_CompareWithCTD_247dBar_20200212to20200828
ccff

## DFO3
Only one profile was completed at the retrieval
### Salinity
image

### Temperature
image

### Dissolved Oxygen
image

### CODE REVIEW

**Review by n-a-t-e — APPROVED** [review]

**Comment by JessyBarrette** [comment]
Please Jen have a look at the present analysis of the data from the Rivers Inlet mooring and the metadata associated.

**Comment by JessyBarrette** [comment]
profile vs mooring analysis can be retrieved here:
https://colab.research.google.com/drive/1bKw4yZNomDopiBXAoqX7de5AK1jYj51P?usp=sharing

**Comment by jenjax2** [comment]
These look pretty good @JessyBarrette thanks for sharing them. Any idea why the oxygen sensor was so off during the DFO3 retrieval in August 2020? Do you think it's the mooring oxygen or the CTD oxygen that is off?

**Comment by raytula** [comment]
> profile vs mooring analysis can be retrieved here: https://colab.research.google.com/drive/1bKw4yZNomDopiBXAoqX7de5AK1jYj51P?usp=sharing

Hey @JessyBarrette could you share this with me as well.  I'd like to have a look.  Thanks

**Comment by JessyBarrette** [comment]
Sorry I'm just catching up on some old exchanges that I never replied to
> > profile vs mooring analysis can be retrieved here: https://colab.research.google.com/drive/1bKw4yZNomDopiBXAoqX7de5AK1jYj51P?usp=sharing
> 
> Hey @JessyBarrette could you share this with me as well. I'd like to have a look. Thanks
Certainly, should have access to it now!

> These look pretty good @JessyBarrette thanks for sharing them. Any idea why the oxygen sensor was so off during the DFO3 > retrieval in August 2020? Do you think it's the mooring oxygen or the CTD oxygen that is off?

Hard to tell, it could be a bit both. A 5% error on the measurement from either instrument is ~0.2mL/L. Considering the two sensors then our error becomes +-0.4mL/L

**Pull request merged**
